version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ec2-user/spring-docker-aws-deploy
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user